### ISSUE TITLE
Archway having issue deploying

### ISSUE THREAD

**Issue by mikedotexe** [CronCats/cw-croncat#393]
When I run `npm run go archwaytestnet` in the `scripts/deployment` directory, I'm getting this:

> croncat-factory-deployment@0.1.0 go
> tsc && cross-env NODE_OPTIONS=--experimental-vm-modules NODE_NO_WARNINGS=1 node build/index.js "archwaytestnet"

```
Error: Invalid gas price string
    at Function.fromString (/Users/mikepurvis/ic/cw-croncat/scripts/deployment/node_modules/@cosmjs/stargate/build/fee.js:38:19)
    at DeploySigner.init (/Users/mikepurvis/ic/cw-croncat/scripts/deployment/build/signer.js:28:52)
    at /Users/mikepurvis/ic/cw-croncat/scripts/deployment/build/index.js:140:53
    at Array.map (<anonymous>)
    at start (/Users/mikepurvis/ic/cw-croncat/scripts/deployment/build/index.js:138:36)
    at /Users/mikepurvis/ic/cw-croncat/scripts/deployment/build/index.js:180:8
    at Object.<anonymous> (/Users/mikepurvis/ic/cw-croncat/scripts/deployment/build/index.js:180:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
``

**Comment by TrevorJTClarke** [comment]
I have fixed in latest
